-- Databricks notebook source
/*---------------------------------------------------------------------------------------------------
# Name: tbl_init_curated_trd_fin_acct_prfl_dly.sql
# Area: trd_fin
#----------------------------------------------------------------------------------------------------
#
# Change Revision
#----------------------------------------------------------------------------------------------------
# Date....           Who....           Description....
#----------------------------------------------------------------------------------------------------
# 2023-10-26         Jirat B.          Initial Version
# 2024-02-15         Jirat B.          Add Curated View
#
# Target table(s)/view(s): ${catalog}.curated_trd_fin.trd_fin_acct_prfl_dly
#--------------------------------------------------------------------------------------------------*/

-- COMMAND ----------

create table if not exists ${catalog}.curated_trd_fin.trd_fin_acct_prfl_dly (
	pos_dt date comment 'Position Date',
	cis_num integer comment 'CIS Number',
	orig_cst_num string comment 'Original Customer Number',
	lpm_num bigint comment 'LPM Number',
	acct_num string comment 'Account Number',
	orig_acct_num string comment 'Original Account Number',
	acct_st_cd string comment 'Account Status Code',
	issu_dt date comment 'Issue Date',
	acct_cls_dt date comment 'Account Close Date',
	coa_pd_ftr_cd integer comment 'COA Product Feature Code',
	coa_pd_cd string comment 'COA Product Code',
	coa_pnp_amt_cd string comment 'COA Principal Amount Code',
	acct_ownr_tp_cd string comment 'Account Ownership Type Code',
	cntg_f string comment 'Contingent Flag',
	acct_eff_dt date comment 'Account Effective Date',
	val_dt date comment 'Value Date',
	mat_dt date comment 'Maturity Date',
	tenor_priod decimal(5, 0) comment 'Tenor Period',
	tenor_unit string comment 'Tenor Unit',
	orig_term_in_day integer comment 'Original Term in Days',
	rmain_term_in_day integer comment 'Remaining Term in Days',
	open_in_mo_f string comment 'Open in Month Flag',
	cls_in_mo_f string comment 'Close in Month Flag',
	due_dt date comment 'Due Date',
	ccy_cd string comment 'Currency Code',
	kbnk_mid_rate decimal(11, 7) comment 'KBANK Mid Rate',
	orig_book_bal_thb decimal(18, 2) comment 'Original Book Balance in THB',
	orig_book_bal_orig_ccy decimal(18, 2) comment 'Original Book Balance in Original Currency',
	crrnt_book_bal_thb decimal(18, 2) comment 'Current Book Balance in THB',
	crrnt_book_bal_orig_ccy decimal(18, 2) comment 'Current Book Balance in Original Currency',
	mtd_accum_dly_avg_book_bal_thb decimal(18, 2) comment 'MTD Accumulated Daily Average Book Balance in THB',
	mtd_accum_dly_avg_book_bal_orig_ccy decimal(18, 2) comment 'MTD Accumulated Daily Average Book Balance in Original Currency',
	orig_par_bal decimal(18, 2) comment 'Original Par Balance',
	crrnt_par_bal decimal(18, 2) comment 'Current Par Balance',
	mtd_accum_dly_avg_par_bal_thb decimal(18, 2) comment 'MTD Accumulated Daily Average Par Balance in THB',
	mtd_accum_dly_avg_par_bal_orig_ccy decimal(18, 2) comment 'MTD Accumulated Daily Average Par Balance in Original Currency',
	orig_pnp_amt_thb decimal(18, 2) comment 'Original Principal Amount in THB',
	orig_pnp_amt_orig_ccy decimal(18, 2) comment 'Original Principal Amount in Original Currency',
	pnp_amt_orig_ccy decimal(18, 2) comment 'Principal Amount in Original Currency',
	crrnt_pnp_amt_orig_ccy decimal(18, 2) comment 'Current Principal Amount in Original Currency',
	otsnd_amt_orig_ccy decimal(17, 2) comment 'Outstanding Amount in Original Currency',
	otsnd_int_amt_thb decimal(18, 2) comment 'Outstanding Interest Amount in THB',
	otsnd_int_amt_orig_ccy decimal(18, 2) comment 'Outstanding Interest Amount in Original Currency',
	discnt_tp_cd string comment 'Discount Type Code',
	orig_premm_discnt_thb decimal(18, 2) comment 'Original Premium or Discount in THB',
	orig_premm_discnt_amt_orig_ccy decimal(18, 2) comment 'Original Premium or Discount Amount in Original Currency',
	crrnt_premm_discnt_amt_thb decimal(18, 2) comment 'Current Premium/Discount Amount in THB',
	crrnt_premm_discnt_amt_orig_ccy decimal(18, 2) comment 'Current Premium/Discount Amount in Original Currency',
	dep_dedct_acct_num bigint comment 'Deposit Deduct Account Number',
	last_paymt_dt date comment 'Last Payment Date',
	last_paymt_amt_thb decimal(18, 2) comment 'Last Payment Amount in THB',
	last_paymt_amt_orig_ccy decimal(18, 2) comment 'Last Payment Amount in Original Currency',
	accum_all_paymt_amt_thb bigint comment 'Accumulated All Payment Amount in THB',
	accum_all_paymt_amt_orig_ccy bigint comment 'Accumulated All Payment Amount in Original Currency',
	last_pnp_paymt_dt date comment 'Last Principal Payment Date',
	nxt_pnp_paymt_dt date comment 'Next Principal Payment Date',
	prepaymt_cd string comment 'Prepayment Code',
	prepaymt_dt date comment 'Prepayment Date',
	prepaymt_amt_thb decimal(18, 2) comment 'Prepayment Amount in THB',
	prepaymt_amt_orig_ccy decimal(18, 2) comment 'Prepayment Amount in Original Currency',
	fee_amt decimal(9, 2) comment 'Fee Amount',
	unpaid_fee_thb decimal(18, 2) comment 'Unpaid Fee in THB',
	grc_f string comment 'Grace Flag',
	grc_priod_strt_dt date comment 'Grace Period Start Date',
	grc_priod_end_dt date comment 'Grace Period End Date',
	int_cal_f string comment 'Interest Calculation Flag',
	int_cal_end_dt date comment 'Interest Calculation End Date',
	int_paymt_frq_tp_cd smallint comment 'Interest Payment Frequency Type Code',
	int_paymt_frq decimal(5, 2) comment 'Interest Payment Frequency',
	last_int_paymt_dt date comment 'Last Interest Payment Date',
	int_amt decimal(17, 2) comment 'Interest Amount',
	int_rcv_amt_thb decimal(18, 2) comment 'Interest Received Amount in THB',
	int_rcv_amt_orig_ccy decimal(18, 2) comment 'Interest Received Amount in Original Currency',
	acru_basis_cd integer comment 'Accrued Basis Code',
	acru_int_amt_thb decimal(18, 2) comment 'Accrued Interest Amount in THB',
	dly_acru_int_amt_orig_ccy decimal(18, 2) comment 'Daily Accrued Interest Amount in Original Currency',
	int_priod integer comment 'Interest period',
	avg_int_priod_pnp_amt decimal(18, 2) comment 'Average Interest Period Principal Amount',
	nxt_int_paymt_dt date comment 'Next Interest Payment Date',
	int_chng_cd smallint comment 'Interest Change Code',
	max_int_rate decimal(9, 7) comment 'Maximum Interest Rate',
	orig_int_rate_pct decimal(9, 7) comment 'Original Interest Rate Percentage',
	int_rate_tp_cd integer comment 'Interest Rate Type Code',
	int_rate_tp_desc string comment 'Interest Rate Type Description',
	mtd_wght_avg_indx_rate decimal(9, 5) comment 'MTD Weighted Average Index Rate',
	crrnt_int_rate_tp_cd string comment 'Current Interest Rate Type Code',
	crrnt_int_rate_pct decimal(9, 7) comment 'Current Interest Rate Percentage',
	sprd_pct decimal(9, 7) comment 'Spread Percentage',
	late_int_chrg_rate_pct decimal(9, 7) comment 'Late Interest Charge Rate Percentage',
	dly_late_int_chrg_amt decimal(18, 2) comment 'Daily Late Interest Charge Amount',
	dly_late_int_chrg_amt_orig_ccy decimal(18, 2) comment 'Daily Late Interest Charge Amount in Original Currency',
	rmain_late_int_chrg_amt decimal(18, 2) comment 'Remaining Late Interest Charge Amount',
	rmain_late_int_chrg_amt_orig_ccy decimal(18, 2) comment 'Remaining Late Interest Charge Amount in Original Currency',
	orig_admn_rate_pct decimal(9, 7) comment 'Original Admin Rate Percentage',
	crrnt_indx_rate_pct decimal(9, 7) comment 'Current Index Rate Percentage',
	amtz_tp_cd string comment 'Amortization Type Code',
	amtz_amt_thb decimal(18, 2) comment 'Amortized Amount in THB',
	amtz_amt_orig_ccy decimal(18, 2) comment 'Amortized Amount in Original Currency',
	ovdue_f string comment 'Overdue Flag',
	ovdue_dt date comment 'Overdue Date',
	ovdue_amt_thb decimal(18, 2) comment 'Overdue Amount in THB',
	ovdue_amt_orig_ccy decimal(18, 2) comment 'Overdue Amount in Original Currency',
	dpd integer comment 'Days Past Due',
	pnp_dpd integer comment 'Principal Days Past Due',
	int_dpd integer comment 'Interest Days Past Due',
	dpd_bot integer comment 'Days Past Due of BOT',
	rvrs_acru_int_f string comment 'Reverse Accrued Interest Flag',
	rvrs_acru_int_dt date comment 'Reverse Accrued Interest Date',
	reprc_frq_cd decimal(4, 2) comment 'Repricing Frequency Code',
	last_rprc_dt date comment 'Last Reprice Date',
	last_rprc_amt decimal(18, 2) comment 'Last Reprice Amount',
	nxt_rprc_dt date comment 'Next Reprice Date',
	fclty_id string comment 'Facility ID',
	lmt_acct_num string comment 'Limit Account Number',
	crrnt_fclty_lmt_lvl string comment 'Current Facility Limit Level',
	lmt_acct_num_lvl_6 string comment 'Limit Account Number Level 6',
	lmt_amt decimal(18, 2) comment 'Limit Amount',
	hub_num integer comment 'Hub Number',
	load_tms timestamp comment 'Load Timestamp',
	ptn_yyyy string comment 'Partition Year',
	ptn_mm string comment 'Partition Month',
	ptn_dd string comment 'Partition Day',
	ptn_src_sys_id string comment 'Partition Source System Identification'
) using delta partitioned by (ptn_yyyy, ptn_mm, ptn_dd, ptn_src_sys_id) location 'abfss://${storage_curated}/${catalog}/curated_trd_fin/trd_fin_acct_prfl_dly' tblproperties (
	'delta.minreaderversion' = '2',
	'delta.minwriterversion' = '5',
	'delta.columnmapping.mode' = 'name'
)
