-- Databricks notebook source
/*---------------------------------------------------------------------------------------------------
# Name: view_init_curated_v_trd_fin_acct_prfl_dly.sql
# Area: trd_fin
#----------------------------------------------------------------------------------------------------
#
# Change Revision
#----------------------------------------------------------------------------------------------------
# Date....           Who....           Description....
#----------------------------------------------------------------------------------------------------
# 2023-10-26         Jirat B.          Initial Version
# 2024-02-15         Jirat B.          Add Curated View
#
# Target table(s)/view(s): ${catalog}.curated_trd_fin_view.v_trd_fin_acct_prfl_dly
#--------------------------------------------------------------------------------------------------*/

-- COMMAND ----------

create or replace view ${catalog}.curated_trd_fin_view.v_trd_fin_acct_prfl_dly as
select
	pos_dt as pos_dt,
	cis_num as cis_num,
	orig_cst_num as orig_cst_num,
	lpm_num as lpm_num,
	acct_num as acct_num,
	orig_acct_num as orig_acct_num,
	acct_st_cd as acct_st_cd,
	issu_dt as issu_dt,
	acct_cls_dt as acct_cls_dt,
	coa_pd_ftr_cd as coa_pd_ftr_cd,
	coa_pd_cd as coa_pd_cd,
	coa_pnp_amt_cd as coa_pnp_amt_cd,
	acct_ownr_tp_cd as acct_ownr_tp_cd,
	cntg_f as cntg_f,
	acct_eff_dt as acct_eff_dt,
	val_dt as val_dt,
	mat_dt as mat_dt,
	tenor_priod as tenor_priod,
	tenor_unit as tenor_unit,
	orig_term_in_day as orig_term_in_day,
	rmain_term_in_day as rmain_term_in_day,
	open_in_mo_f as open_in_mo_f,
	cls_in_mo_f as cls_in_mo_f,
	due_dt as due_dt,
	ccy_cd as ccy_cd,
	kbnk_mid_rate as kbnk_mid_rate,
	orig_book_bal_thb as orig_book_bal_thb,
	orig_book_bal_orig_ccy as orig_book_bal_orig_ccy,
	crrnt_book_bal_thb as crrnt_book_bal_thb,
	crrnt_book_bal_orig_ccy as crrnt_book_bal_orig_ccy,
	mtd_accum_dly_avg_book_bal_thb as mtd_accum_dly_avg_book_bal_thb,
	mtd_accum_dly_avg_book_bal_orig_ccy as mtd_accum_dly_avg_book_bal_orig_ccy,
	orig_par_bal as orig_par_bal,
	crrnt_par_bal as crrnt_par_bal,
	mtd_accum_dly_avg_par_bal_thb as mtd_accum_dly_avg_par_bal_thb,
	mtd_accum_dly_avg_par_bal_orig_ccy as mtd_accum_dly_avg_par_bal_orig_ccy,
	orig_pnp_amt_thb as orig_pnp_amt_thb,
	orig_pnp_amt_orig_ccy as orig_pnp_amt_orig_ccy,
	pnp_amt_orig_ccy as pnp_amt_orig_ccy,
	crrnt_pnp_amt_orig_ccy as crrnt_pnp_amt_orig_ccy,
	otsnd_amt_orig_ccy as otsnd_amt_orig_ccy,
	otsnd_int_amt_thb as otsnd_int_amt_thb,
	otsnd_int_amt_orig_ccy as otsnd_int_amt_orig_ccy,
	discnt_tp_cd as discnt_tp_cd,
	orig_premm_discnt_thb as orig_premm_discnt_thb,
	orig_premm_discnt_amt_orig_ccy as orig_premm_discnt_amt_orig_ccy,
	crrnt_premm_discnt_amt_thb as crrnt_premm_discnt_amt_thb,
	crrnt_premm_discnt_amt_orig_ccy as crrnt_premm_discnt_amt_orig_ccy,
	dep_dedct_acct_num as dep_dedct_acct_num,
	last_paymt_dt as last_paymt_dt,
	last_paymt_amt_thb as last_paymt_amt_thb,
	last_paymt_amt_orig_ccy as last_paymt_amt_orig_ccy,
	accum_all_paymt_amt_thb as accum_all_paymt_amt_thb,
	accum_all_paymt_amt_orig_ccy as accum_all_paymt_amt_orig_ccy,
	last_pnp_paymt_dt as last_pnp_paymt_dt,
	nxt_pnp_paymt_dt as nxt_pnp_paymt_dt,
	prepaymt_cd as prepaymt_cd,
	prepaymt_dt as prepaymt_dt,
	prepaymt_amt_thb as prepaymt_amt_thb,
	prepaymt_amt_orig_ccy as prepaymt_amt_orig_ccy,
	fee_amt as fee_amt,
	unpaid_fee_thb as unpaid_fee_thb,
	grc_f as grc_f,
	grc_priod_strt_dt as grc_priod_strt_dt,
	grc_priod_end_dt as grc_priod_end_dt,
	int_cal_f as int_cal_f,
	int_cal_end_dt as int_cal_end_dt,
	int_paymt_frq_tp_cd as int_paymt_frq_tp_cd,
	int_paymt_frq as int_paymt_frq,
	last_int_paymt_dt as last_int_paymt_dt,
	int_amt as int_amt,
	int_rcv_amt_thb as int_rcv_amt_thb,
	int_rcv_amt_orig_ccy as int_rcv_amt_orig_ccy,
	acru_basis_cd as acru_basis_cd,
	acru_int_amt_thb as acru_int_amt_thb,
	dly_acru_int_amt_orig_ccy as dly_acru_int_amt_orig_ccy,
	int_priod as int_priod,
	avg_int_priod_pnp_amt as avg_int_priod_pnp_amt,
	nxt_int_paymt_dt as nxt_int_paymt_dt,
	int_chng_cd as int_chng_cd,
	max_int_rate as max_int_rate,
	orig_int_rate_pct as orig_int_rate_pct,
	int_rate_tp_cd as int_rate_tp_cd,
	int_rate_tp_desc as int_rate_tp_desc,
	mtd_wght_avg_indx_rate as mtd_wght_avg_indx_rate,
	crrnt_int_rate_tp_cd as crrnt_int_rate_tp_cd,
	crrnt_int_rate_pct as crrnt_int_rate_pct,
	sprd_pct as sprd_pct,
	late_int_chrg_rate_pct as late_int_chrg_rate_pct,
	dly_late_int_chrg_amt as dly_late_int_chrg_amt,
	dly_late_int_chrg_amt_orig_ccy as dly_late_int_chrg_amt_orig_ccy,
	rmain_late_int_chrg_amt as rmain_late_int_chrg_amt,
	rmain_late_int_chrg_amt_orig_ccy as rmain_late_int_chrg_amt_orig_ccy,
	orig_admn_rate_pct as orig_admn_rate_pct,
	crrnt_indx_rate_pct as crrnt_indx_rate_pct,
	amtz_tp_cd as amtz_tp_cd,
	amtz_amt_thb as amtz_amt_thb,
	amtz_amt_orig_ccy as amtz_amt_orig_ccy,
	ovdue_f as ovdue_f,
	ovdue_dt as ovdue_dt,
	ovdue_amt_thb as ovdue_amt_thb,
	ovdue_amt_orig_ccy as ovdue_amt_orig_ccy,
	dpd as dpd,
	pnp_dpd as pnp_dpd,
	int_dpd as int_dpd,
	dpd_bot as dpd_bot,
	rvrs_acru_int_f as rvrs_acru_int_f,
	rvrs_acru_int_dt as rvrs_acru_int_dt,
	reprc_frq_cd as reprc_frq_cd,
	last_rprc_dt as last_rprc_dt,
	last_rprc_amt as last_rprc_amt,
	nxt_rprc_dt as nxt_rprc_dt,
	fclty_id as fclty_id,
	lmt_acct_num as lmt_acct_num,
	crrnt_fclty_lmt_lvl as crrnt_fclty_lmt_lvl,
	lmt_acct_num_lvl_6 as lmt_acct_num_lvl_6,
	lmt_amt as lmt_amt,
	hub_num as hub_num,
	load_tms as load_tms,
	ptn_yyyy as ptn_yyyy,
	ptn_mm as ptn_mm,
	ptn_dd as ptn_dd,
	ptn_src_sys_id as ptn_src_sys_id
from ${catalog}.curated_trd_fin.trd_fin_acct_prfl_dly
